apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  namespace: udagram
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: nginx
        image: basugaurab88/reverseproxy:v4
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always